{
 "title": "BNG State and Resource Availability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "SRRP Redundancy",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|~ \"srrp.*oper-state\" \n| json bngRouter=\"source\"\n| bngRouter=~\".*bng1.*\"\n| json operState=`updates[0].values[\"oper-state\"]`\n| label_format BNG1_OperState=\"{{.bngRouter}} {{.operState}}\""
    },
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|~ \"srrp.*oper-state\" \n| json bngRouter=\"source\"\n| bngRouter=~\".*bng2.*\"\n| json operState=`updates[0].values[\"oper-state\"]`\n| label_format BNG2_OperState=\"{{.bngRouter}} {{.operState}}\""
    }
   ]
  },
  {
   "title": "Number of current IPv4 / IPv6 hosts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_current_value{total_hosts_counter=\"ipv4\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    },
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_current_value{total_hosts_counter=\"ipv6\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    }
   ]
  },
  {
   "title": "Syslog Event Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (application, level, source) (count_over_time({job=\"syslog\"}[$__auto]))",
     "legendFormat": "{{application}} {{level}} {{source}}"
    }
   ]
  },
  {
   "title": "Peak IPv4 / IPv6 hosts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_peak_value{total_hosts_counter=\"ipv4\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    },
    {
     "expr": "state_subscriber_mgmt_statistics_total_hosts_peak_value{total_hosts_counter=\"ipv6\"}",
     "legendFormat": "{{source}} {{total_hosts_counter}}"
    }
   ]
  },
  {
   "title": "Syslog",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog\"}"
    }
   ]
  },
  {
   "title": "SAP instances allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "state_card_mda_resource_usage_sap_instances_allocated{mda_mda_slot=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "BNG CPU Usage, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"60\", source=~\".*bng[1,2]\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Memory Used, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use / on(source) (state_system_memory_pools_summary_total_in_use + on(source) state_system_memory_pools_summary_available_memory) * 100",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Igress / Egress Queues allocated, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( state_card_fp_resource_usage_egress_queues_allocated/ on (source) state_card_fp_resource_usage_egress_queues_total) * 100",
     "legendFormat": "{{source}} ingress"
    },
    {
     "expr": "(state_card_fp_resource_usage_ingress_queues_allocated / on (source) state_card_fp_resource_usage_egress_queues_total) * 100",
     "legendFormat": "{{source}} egress"
    }
   ]
  },
  {
   "title": "Ingress Port Rates on BNG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_in_octets{subscription_name=\"sros-router-interfaces\", source=~\".*bng[1,2]\", port_port_id=~\"1/1/.*/1\"}[60s]) * 8 / 60000",
     "legendFormat": "in {{port_port_id}} {{source}}"
    }
   ]
  },
  {
   "title": "Igress / Egress Policers allocated, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( state_card_fp_resource_usage_egress_policers_allocated / on (source) state_card_fp_resource_usage_egress_policers_total) * 100",
     "legendFormat": "{{source}} ingress"
    },
    {
     "expr": "( state_card_fp_resource_usage_ingress_policers_allocated / on (source) state_card_fp_resource_usage_ingress_policers_total) * 100",
     "legendFormat": "{{source}} egress"
    }
   ]
  },
  {
   "title": "Egress Port Rates on BNG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_out_octets{subscription_name=\"sros-router-interfaces\", source=~\".*bng[1,2]\", port_port_id=~\"1/1/.*/1\"}[60s]) * 8 / 60000",
     "legendFormat": "in {{port_port_id}} {{source}}"
    }
   ]
  },
  {
   "title": "Total PPP session established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"ppp-sessions-total-established\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Master / NoN Master Transitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_master{source=\"clab-sros_bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become Master {{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_master{source=\"clab-sros_bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become Master {{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_non_master{source=\"clab-sros_bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become NoN Master {{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_become_non_master{source=\"clab-sros_bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "Become NoN Master {{source}}"
    }
   ]
  },
  {
   "title": "SRRP Adv. Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_discards{source=\"clab-sros_bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_discards{source=\"clab-sros_bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Node Availability (MGMT)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smokeping_send_errors_total{host=\"clab-sros_bngt-bng1\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "smokeping_send_errors_total{host=\"clab-sros_bngt-bng2\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SRRP Adv. Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_errors{source=\"clab-sros_bngt-bng1\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "state_service_vprn_subscriber_interface_group_interface_srrp_statistics_advertisement_interval_errors{source=\"clab-sros_bngt-bng2\", srrp_srrp_id=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Next hop resource entries consumed, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( state_system_resource_usage_subscriber_next_hop_entries_allocated{subscription_name=\"sros-system-resources\"} / on (source) state_system_resource_usage_subscriber_next_hop_entries_total{subscription_name=\"sros-system-resources\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}