global:
  scrape_interval:     5s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - tel-am:9093

scrape_configs:
  - job_name: smokeping
    static_configs:
      - targets: ['tel-sping:9374']

  - job_name: sros_bngt_gnmic
    static_configs:
      - targets: ['gnmic-metrics:9274']