username: admin

# Credentials
auth_cred: &auth_cred
  username: admin
  password: admin
  port: 57400
  timeout: 10s
  skip-verify: true
  insecure: true

# GRPC mode
mode_stream: &mode_stream
  mode: stream
  stream-mode: sample
  sample-interval: 5s
  encoding: JSON

# List of subscriptions
sub_bng: &sub_bng
  - sros-system-performance
  - sros-sub-mgmt-statistics
  - sros-fp-sub-mgmt-resources
  - sros-system-resources
  - sros-sub-mgmt-subscribers
  - sros-sub-mgmt-redundnacy
  - sros-router-interfaces

sub_core_agg: &sub_core_agg
  - sros-system-performance
  - sros-router-interfaces

# Targets
targets:
  clab-sros_bngt-bng1:
    <<: *auth_cred
    subscriptions:
      *sub_bng
  clab-sros_bngt-bng2:
    <<: *auth_cred
    subscriptions:
      *sub_bng
  clab-sros_bngt-agg:
    <<: *auth_cred
    subscriptions:
      *sub_core_agg
  clab-sros_bngt-core:
    <<: *auth_cred
    subscriptions:
      *sub_core_agg

# Definitions of subscriptions
subscriptions:
  sros-system-performance:
    <<: *mode_stream
    paths:
      - /state/system/cpu[sample-period=60]/summary/usage
      - /state/system/memory-pools/summary/available-memory
      - /state/system/memory-pools/summary/current-total-size
      - /state/system/memory-pools/summary/total-in-use
  
  sros-sub-mgmt-statistics:
    <<: *mode_stream
    paths:
      - /state/subscriber-mgmt/statistics/sessions[counter=ppp-sessions-total-established]/current-value
      - /state/subscriber-mgmt/statistics/total-hosts[counter=ipv4]
      - /state/subscriber-mgmt/statistics/total-hosts[counter=ipv6]

  sros-fp-sub-mgmt-resources:
    <<: *mode_stream
    paths:
      - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/egress-queues
      - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/ingress-queues
      - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/ingress-policers
      - /state/card[slot-number=1]/fp[fp-number=1]/resource-usage/egress-policers
      - /state/card[slot-number=1]/mda[mda-slot=1]/resource-usage/sap-instances
  
  sros-sub-mgmt-subscribers:
    <<: *mode_stream
    paths:
      - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/up-time
      - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/ipv4/forwarding-state
      - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/ipv6/pd/forwarding-state
      - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/session[type=ppp][id=*]/ipv6/slaac/forwarding-state
      - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/ingress/qos/statistics/out-profile-forwarded-octets
      - /state/subscriber-mgmt/subscriber[subscriber-id=*]/sla-profile-instance[id=*]/egress/qos/statistics/out-exceed-profile-forwarded-octets

  
  sros-system-resources:
    <<: *mode_stream
    paths:
      - /state/system/resource-usage/subscriber-next-hop-entries
  
  sros-sub-mgmt-redundnacy:
    <<: *mode_stream
    paths:
      - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/advertisement-interval-errors
      - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/advertisement-interval-discards
      - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/master-changes
      - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/become-master
      - /state/service/vprn[service-name=BNG-INTERNET]/subscriber-interface[interface-name=SUB]/group-interface[group-interface-name=GRP_1]/srrp[srrp-id=1]/statistics/become-non-master
  
  sros-router-interfaces:
    <<: *mode_stream
    paths:
    # port and interface utilisation
      - /state/router[router-name=*]/interface[interface-name=*]/statistics/ip/in-octets
      - /state/router[router-name=*]/interface[interface-name=*]/statistics/ip/out-octets
      - /state/router[router-name=*]/interface[interface-name=*]/statistics/mpls/in-octets
      - /state/router[router-name=*]/interface[interface-name=*]/statistics/mpls/out-octets
      - /state/port[port-id=*]/ethernet/statistics/in-octets
      - /state/port[port-id=*]/ethernet/statistics/out-octets
      - /state/port[port-id=*]/ethernet/statistics/in-utilization
      - /state/port[port-id=*]/ethernet/statistics/out-utilization
      - /state/port[port-id=*]/oper-state


outputs:
  op-prometheus:
    type: prometheus
    listen: 0.0.0.0:9274
    event-processors:
      - oper-state-to-int
  op-stdout:
    type: file # output type
    file-type: stdout # or stderr
    format: json
    event-processors:
      - oper-state-to-int

processors:
  oper-state-to-int:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
